import { createUseStyles } from 'react-jss';

const FromStyles = createUseStyles({
  Form: {
    boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.25)',
    borderRadius: 10,
    backgroundColor: 'white',
    marginTop: 43,
    marginBottom: 43,
    width: '90.625%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  FromContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '93.103448275%',
    marginBottom: 33,
  },
  FormCrossContainer: {
    width: '100%',
    display: 'flex',
    justifyContent: 'flex-end',
    marginTop: 0,
  },
  FormCross: {
    height: 15,
    fontSize: 45,
    marginBottom: 15,
    color: 'rgba(0, 0, 0, 0.25)',
    cursor: 'pointer',
    WebkitTouchCallout: 'none' /* iOS Safari */,
    WebkitUserSelect: 'none' /* Chrome/Safari/Opera */,
    KhtmlUserSelect: 'none' /* Konqueror */,
    MozUserSelect: 'none' /* Firefox */,
    msUserSelect: 'none' /* Internet Explorer/Edge */,
    userSelect: 'none',
    // width: 'auto',
  },
  FormTitle: {
    width: '59.259259259%',
    // marginTop: 30,
    fontSize: 28,
    fontWeight: 500,
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'SF-pro-medium',
  },
  PaymentTitle: {
    alignSelf: 'flex-start',
    fontSize: 14,
    marginTop: 25,
    marginBottom: 15,
    fontFamily: 'SF-pro-light',
  },
  FormPayment: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    width: '100%',
    height: 125,
    alignItems: 'center',
  },
  ExtraButton: {
    color: '#014488',
    fontSize: 21,
    fontWeight: 500,
    alignSelf: 'flex-start',
    marginTop: 25,
    marginBottom: 25,
    fontFamily: 'SF-pro-medium',
    cursor: 'pointer',
    WebkitTouchCallout: 'none' /* iOS Safari */,
    WebkitUserSelect: 'none' /* Chrome/Safari/Opera */,
    KhtmlUserSelect: 'none' /* Konqueror */,
    MozUserSelect: 'none' /* Firefox */,
    msUserSelect: 'none' /* Internet Explorer/Edge */,
    userSelect: 'none',
  },
  TotalCost: {
    display: 'flex',
    alignSelf: 'flex-start',
    width: '81.034482758%',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    fontFamily: 'SF-pro-light',
  },
  TotalCostText: {
    fontSize: 14,
  },
  FormValid: {
    fontSize: 14,
    color: '#8F0F0F',
    marginBottom: 20,
  },
  FormArrow: {
    transform: (theme) => theme.transform,
    height: 11,
    width: 'auto',
    marginLeft: 7,
  },
});

export default FromStyles;
