const imgs = [];
imgs.push(require('../../../img/Portfolio/Group 558.png'));
imgs.push(require('../../../img/Portfolio/Group 559.png'));
imgs.push(require('../../../img/Portfolio/Group 560.png'));
imgs.push(require('../../../img/Portfolio/Group 561.png'));
imgs.push(require('../../../img/Portfolio/Group 562.png'));
imgs.push(require('../../../img/Portfolio/Group 563.png'));
imgs.push(require('../../../img/Portfolio/Group 564.png'));
imgs.push(require('../../../img/Portfolio/Group 565.png'));
imgs.push(require('../../../img/Portfolio/Group 566.png'));
imgs.push(require('../../../img/Portfolio/Group 567.png'));
imgs.push(require('../../../img/Portfolio/Group 568.png'));
imgs.push(require('../../../img/Portfolio/Group 569.png'));
imgs.push(require('../../../img/Portfolio/Group 570.png'));
imgs.push(require('../../../img/Portfolio/Group 571.png'));
imgs.push(require('../../../img/Portfolio/Group 572.png'));
imgs.push(require('../../../img/Portfolio/Group 573.png'));
imgs.push(require('../../../img/Portfolio/Group 574.png'));
imgs.push(require('../../../img/Portfolio/Group 575.png'));
imgs.push(require('../../../img/Portfolio/Group 576.png'));
imgs.push(require('../../../img/Portfolio/Group 577.png'));
imgs.push(require('../../../img/Portfolio/Group 578.png'));
imgs.push(require('../../../img/Portfolio/Group 579.png'));
imgs.push(require('../../../img/Portfolio/Group 580.png'));
imgs.push(require('../../../img/Portfolio/Group 581.png'));
imgs.push(require('../../../img/Portfolio/Group 582.png'));
imgs.push(require('../../../img/Portfolio/Group 583.png'));
imgs.push(require('../../../img/Portfolio/Group 584.png'));
imgs.push(require('../../../img/Portfolio/Group 585.png'));
imgs.push(require('../../../img/Portfolio/Group 586.png'));

const imgs_2 = [];
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 354.png'));
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 355.png'));
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 365.png'));
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 367.png'));
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 369.png'));
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 371.png'));
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 373.png'));
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 375.png'));
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 377.png'));
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 379.png'));
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 381.png'));
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 383.png'));
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 385.png'));
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 387.png'));
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 389.png'));
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 391.png'));
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 393.png'));
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 395.png'));
imgs_2.push(require('../../../img/Signatures/Desktop/Frame 397.png'));

const imgs_3 = [];
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 421.png'));
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 511.png'));
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 512.png'));
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 513.png'));
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 514.png'));
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 515.png'));
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 516.png'));
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 517.png'));
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 518.png'));
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 519.png'));
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 520.png'));
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 521.png'));
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 522.png'));
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 523.png'));
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 524.png'));
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 525.png'));
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 526.png'));
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 527.png'));
imgs_3.push(require('../../../img/Signatures/Mobile/Frame 528.png'));

export { imgs, imgs_2, imgs_3 };
